inherit: true

tools:
    php_code_coverage: false
    php_code_sniffer:
        enabled: true
        config:
            sniffs:
                squiz:
                    php:
                        commented_out_code_sniff: false
    php_cpd: true
    php_cs_fixer: true
    php_loc: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true