version: '2'

services:
  node:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: wmde/data-bridge-node
    volumes:
      - '~/.npm:/.npm'
      - './:/app'
    working_dir: /app
    environment:
      - NODE_ENV
      - NODE_DEBUG
      - DEBUG
